kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
   - role: control-plane  # Control plane node
     extraMounts:
     - hostPath: /home/tietoevry/data
       containerPath: /tmp/data
   - role: worker        # Worker node
     extraPortMappings:
     - containerPort: 31760
       hostPort: 8080
     - containerPort: 31761
       hostPort: 8443
     extraMounts:
     - hostPath: /home/tietoevry/data2
       containerPath: /tmp/data