[general]
dmaapEnabled=true
baseUrl=http://localhost:8181
sdnrUser=admin
sdnrPasswd=${ODL_ADMIN_PASSWORD}

[strimzi-kafka]
strimziEnabled=true
bootstrapServers=kafka-1-kafka-bootstrap.nonrtric:9092
securityProtocol=PLAINTEXT
saslMechanism=PLAIN
saslJaasConfig=PLAIN

[fault]
TransportType=HTTPNOAUTH
host=message-router.nonrtric:3904
topic=unauthenticated.SEC_FAULT_OUTPUT
contenttype=application/json
group=myG
id=C1
timeout=2000
limit=1000
fetchPause=5000

[pnfRegistration]
TransportType=HTTPNOAUTH
host=message-router.nonrtric:3904
topic=unauthenticated.VES_PNFREG_OUTPUT
contenttype=application/json
group=myG
id=C1
timeout=2000
limit=1000
fetchPause=5000

[provisioning]
TransportType=HTTPNOAUTH
host=message-router.nonrtric:3904
topic=unauthenticated.SEC_3GPP_PROVISIONING_OUTPUT
contenttype=application/json
group=myG
id=C1
timeout=20000
limit=10000
fetchPause=5000

[stndDefinedFault]
TransportType=HTTPNOAUTH
host=message-router.nonrtric:3904
topic=unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT
consumerGroup=myG
consumerID=C1
timeout=20000
limit=10000
fetchPause=5000