#  ============LICENSE_START===============================================
#  Copyright (C) 2023 Open Networking Foundation. All rights reserved.
#  Copyright (C) 2023 Tietoevry. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: odlux
  namespace: nonrtric
  labels:
    run: odlux
spec:
  selector:
    matchLabels:
      run: odlux
  template:
    metadata:
      labels:
        run: odlux
    spec:
      containers:
      - name: odlux
        image: nexus3.onap.org:10001/onap/sdnc-web-image:2.6.1
        imagePullPolicy: IfNotPresent
        env:
        - name: WEBPROTOCOL
          value: "HTTP"
        - name: ENABLE_OAUTH
          value: "false"
        - name: WEBPORT
          value: "8080"
        - name: SDNRPROTOCOL
          value: "http"
        - name: SDNRHOST
          value: controller.nonrtric
        - name: SDNRPORT
          value: "8181"
        - name: SDNRWEBSOCKETPORT
          value: "8182"
        ports:
        - name: http
          containerPort: 8080
