#  ============LICENSE_START===============================================
#  Copyright (C) 2023 Nordix Foundation. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#

apiVersion: v1
kind: Pod
metadata:
  name: es-rapp
  namespace: nonrtric
  labels:
    app: es-rapp
spec:
  containers:
  - name: es-rapp
    image: busybox #localhost:5000/es-rapp:latest
    command: ["sleep", "infinity"]
    imagePullPolicy: Always
    env:
    - name: SDN_CONTROLLER_ADDRESS
      value: "172.17.0.1"
    - name: SDN_CONTROLLER_PORT
      value: "80"
    - name: SDN_CONTROLLER_USERNAME
      value: "root"
    - name: SDN_CONTROLLER_PASSWORD
      value: "viavi"
    - name: A1T_ADDRESS
      value: "172.17.0.1"
    - name: A1T_PORT
      value: "80"
    - name: LOAD_PREDICTOR
      value: "dummy"
    - name: LOAD_PREDICTOR_PORT
      value: "dummy"
    - name: LOAD_PREDICTOR_API
      value: "predict"
    - name: RANSIM_DATA_PATH
      value: /input/prb_usage_reports
    - name: CREDS_CLIENT_SECRET
      value: {{ .Values.esrapp.clientsecret }}
    - name: CREDS_CLIENT_ID
      value: es-rapp
    - name: AUTH_SERVICE_URL
      value: http://keycloak.nonrtric/realms/nonrtric-realm/protocol/openid-connect/token
    - name: TOPIC
      value: forward-rapp-topic
    - name: KAFKA_SERVER
      value: kafka-1-kafka-bootstrap.nonrtric:9097
    - name: FUNC
      value: "f2"
    volumeMounts:
    - mountPath: /input/prb_usage_reports
      name: shared-data2

  volumes:
  - configMap:
      name: pm-rapp-jobdef
    name: pm-rapp-jobdef
  - name: shared-data2
    emptyDir: {}
