
name: Submodule atoken CI

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        ls -la
        
    - name: Build atoken Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd atoken
        ls -la
        cd auth-token-fetch
        ls -la
        docker build -t ios-mcn-smo/nonrtric-plt-auth-token-fetch .
      
    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Login to GitHub Container Registry (ghcr.io) for push
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ secrets.GHCRUSER }}
        password: ${{ secrets.GHCRPASS }}

    - name: Tag & Push Docker Images
      run: |
        docker tag ios-mcn-smo/nonrtric-plt-auth-token-fetch:latest ghcr.io/ios-mcn-smo/nonrtric-plt-auth-token-fetch:latest
        docker tag ios-mcn-smo/nonrtric-plt-auth-token-fetch:latest ghcr.io/ios-mcn-smo/nonrtric-plt-auth-token-fetch:1.1.1
        docker push ghcr.io/ios-mcn-smo/nonrtric-plt-auth-token-fetch:latest
        docker push ghcr.io/ios-mcn-smo/nonrtric-plt-auth-token-fetch:1.1.1
