name: Submodule sdnc-oam CI

on:
  workflow_dispatch:

env:
  GHCR_REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true

    # Set up Java 
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Download settings.xml at .m2 Directory
      run: |
        cd 
        ls -la
        cd .m2
        rm settings.xml
        wget https://git.onap.org/oparent/plain/settings.xml
        
    - name: Build sdnc-oam Docker Images
      run: |
        ls -la
        cd deps
        ls -la
        cd sdnc-oam
        ls -la
        mvn clean install -P docker -Ddocker.pull.registry=nexus3.onap.org:10001

    - name: Show The Build Docker Images
      run: |
        docker images

    - name: Login to GitHub Container Registry (ghcr.io) for push
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ secrets.GHCRUSER }}
        password: ${{ secrets.GHCRPASS }}
       
    - name: Tag & Push Docker Images
      run: |
        docker tag onap/sdnc-image:2.6.1-SNAPSHOT-latest ghcr.io/ios-mcn-smo/sdnc-image:2.6.1
        docker tag onap/sdnc-image:latest ghcr.io/ios-mcn-smo/sdnc-image:latest
        docker tag onap/sdnc-web-image:2.6.1-SNAPSHOT-latest ghcr.io/ios-mcn-smo/sdnc-web-image:2.6.1
        docker tag onap/sdnc-web-image:latest ghcr.io/ios-mcn-smo/sdnc-web-image:latest
        docker push ghcr.io/ios-mcn-smo/sdnc-image:2.6.1
        docker push ghcr.io/ios-mcn-smo/sdnc-image:latest
        docker push ghcr.io/ios-mcn-smo/sdnc-web-image:2.6.1
        docker push ghcr.io/ios-mcn-smo/sdnc-web-image:latest
